--MODULE  USER DETAILS
 

CREATE TABLE USER_DETAILS(USER_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
                          NAME VARCHAR2(50) NOT NULL,EMAIL VARCHAR2(100)NOT NULL,
                          PASSWORD VARCHAR2(50)NOT NULL,MOBILE_NUMBER NUMBER NOT NULL,
                          ROLE VARCHAR2(30) DEFAULT 'USER',UNIQUE(EMAIL),
                          CONSTRAINT PK_USERID PRIMARY KEY (USER_ID));
DESC USER_DETAILS;
DROP TABLE USER_DETAILS;
 
INSERT INTO USER_DETAILS (NAME,EMAIL, PASSWORD, MOBILE_NUMBER)
                   VALUES('Dharshini','dharshi05@gmail.com','dharsh123' ,9876543210);
INSERT INTO USER_DETAILS (NAME,EMAIL, PASSWORD, MOBILE_NUMBER)
                   VALUES('Priya', 'priya24@gamail.com','priya123' ,9876543211);
INSERT INTO USER_DETAILS (NAME,EMAIL, PASSWORD, MOBILE_NUMBER)
                   VALUES('Keerthana','keerthi05@gmail.com','keerthi123' ,9876543212);
INSERT INTO USER_DETAILS (NAME,EMAIL, PASSWORD, MOBILE_NUMBER)
                   VALUES('Vishalini','vishali06@gmail.com','vishali123' ,9876543213);
INSERT INTO USER_DETAILS (NAME,EMAIL, PASSWORD, MOBILE_NUMBER)
                   VALUES('Meena','meena13@gmail.com','meena123' ,9876543214);
SELECT * FROM USER_DETAILS;

 

--MODULE  ACCOUNT DETAILS
CREATE  TABLE ACCOUNT_DETAILS(ID NUMBER PRIMARY KEY,ACCOUNT_NUMBER NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 112233445001 INCREMENT BY 1),
                        ACC_TYPE VARCHAR(50) NOT NULL,ACC_HOLDER_NAME VARCHAR(50),ADDRESS VARCHAR(200) NOT NULL,
                        CITY VARCHAR2(20) NOT NULL,PINCODE NUMBER,DOB DATE NOT NULL,
                        MOBILE_NUMBER NUMBER NOT NULL,
                        EMAIL VARCHAR2(100),IFSC_CODE VARCHAR2(50) NOT NULL,BRANCH_NAME VARCHAR(50) NOT NULL,BALANCE NUMBER,
                        PIN_NUMBER NUMBER NOT NULL
                        ,CONSTRAINT FK_MOBNUM FOREIGN KEY(ID) REFERENCES USER_DETAILS(USER_ID));
DESC ACCOUNT_DETAILS;
DROP TABLE ACCOUNT_DETAILS;
SELECT * FROM ACCOUNT_DETAILS;

INSERT INTO ACCOUNT_DETAILS (ID,ACC_TYPE,ACC_HOLDER_NAME,ADDRESS,CITY,PINCODE,DOB,MOBILE_NUMBER,EMAIL,IFSC_CODE,BRANCH_NAME,BALANCE,PIN_NUMBER)
                VALUES(1,'SAVINGS ACCOUNT','Dharshini','15-Nagal Nagar','CHENNAI',600008,'05-03-1999',9876567890,'dharshi05@gmail.com','IB1001100210',
                       'CHENNAI MAIN',10000,1234);
INSERT INTO ACCOUNT_DETAILS (ID,ACC_TYPE,ACC_HOLDER_NAME,ADDRESS,CITY,PINCODE,DOB,MOBILE_NUMBER,EMAIL,IFSC_CODE,BRANCH_NAME,BALANCE,PIN_NUMBER)
                VALUES(2,'SAVINGS ACCOUNT','Priya','16-Ayyanar Nagar','CHENNAI',600008,'24-02-1999',9876567891,'priya24@gmail.com','IB1001100211',
                       'CHENNAI MAIN',20000,2402);
INSERT INTO ACCOUNT_DETAILS (ID,ACC_TYPE,ACC_HOLDER_NAME,ADDRESS,CITY,PINCODE,DOB,MOBILE_NUMBER,EMAIL,IFSC_CODE,BRANCH_NAME,BALANCE,PIN_NUMBER)
                VALUES(3,'CURRENT ACCOUNT','Dharshini','15-Palaniyappa Nagar','CHENNAI',600008,'05-02-2000',9876567892,'keerthi05@gmail.com','IB1001100212',
                       'CHENNAI MAIN',13000,0502);                       
INSERT INTO ACCOUNT_DETAILS (ID,ACC_TYPE,ACC_HOLDER_NAME,ADDRESS,CITY,PINCODE,DOB,MOBILE_NUMBER,EMAIL,IFSC_CODE,BRANCH_NAME,BALANCE,PIN_NUMBER)
                VALUES(4,'SAVINGS ACCOUNT','Vishalini','21-Ram Nagar','CHENNAI',600008,'06-06-1999',9876567893,'vishalini22@gmail.com','IB1001100213',
                       'CHENNAI MAIN',12000,1235);
INSERT INTO ACCOUNT_DETAILS (ID,ACC_TYPE,ACC_HOLDER_NAME,ADDRESS,CITY,PINCODE,DOB,MOBILE_NUMBER,EMAIL,IFSC_CODE,BRANCH_NAME,BALANCE,PIN_NUMBER)
                VALUES(5,'CURRENT ACCOUNT','Meena','31-Nethaji Nagar','CHENNAI',600008,'13-11-1998',9876567894,'meena13@gmail.com','IB1001100214',
                       'CHENNAI MAIN',15000,1311);
                       
                       
SELECT * FROM ACCOUNT_DETAILS;                  
--MODULE  TRANSACTION
CREATE TABLE TRANSACTION(ID INT PRIMARY KEY,ACCOUNT_NUMBER NUMBER,FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT_DETAILS(ACCOUNT_NUMBER),
                         IFSC_CODE NUMBER NOT NULL,TRANSACTION_TYPE VARCHAR(50),AMOUNT NUMBER NOT NULL, BALANCE NUMBER NOT NULL);
drop table transaction;

--MODULE  DEPOSITS(fixed deposit,recurring deposit)
CREATE TABLE DEPOSITS(ID NUMBER PRIMARY KEY,CUSTOMER_ID NUMBER,FOREIGN KEY (CUSTOMER_ID) REFERENCES USER_DETAILS(USER_ID),
                      ACCOUNT_NUMBER NUMBER ,FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT_DETAILS(ACCOUNT_NUMBER),
                      CUSTOMER_TYPE VARCHAR(20) NOT NULL,DEPOSIT_TYPE VARCHAR(30)NOT NULL,AMOUNT NUMBER NOT NULL,
                      DATE_OF_DEPOSIT DATE NOT NULL,TENURE DATE NOT NULL,RATE_OF_INTEREST NUMBER NOT NULL,
                      MATURITY_DATE DATE NOT NULL,MATURITY_VALUE NUMBER NOT NULL);
DESC DEPOSITS;
DROP TABLE DEPOSITS;
SELECT * FROM DEPOSITS;

--MODULE  LOANS
 CREATE TABLE LOANS(LOAN_NUMBER NUMBER PRIMARY KEY,ACCOUNT_NUMBER NUMBER,FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT_DETAILS(ACCOUNT_NUMBER),
                    LOAN_TYPE VARCHAR(50) NOT NULL,DESCRIPTION VARCHAR(100) ,LOAN_AMOUNT NUMBER NOT NULL,TENURE NUMBER NOT NULL,
                    INTEREST_RATE NUMBER NOT NULL,MONTHLY_PAYMENT NUMBER NOT NULL);
 DESC LOANS;
 DROP TABLE LOANS;
 SELECT * FROM LOANS;



 CREATE TABLE ADMIN(ID INT PRIMARY KEY,NAME VARCHAR2(50),PASSWORD VARCHAR2(50),ROLE VARCHAR2(20),
                    CATEGORY VARCHAR2(50) NOT NULL,CATEGORY_TYPE VARCHAR2(50),
                    INTEREST NUMBER NOT NULL);
